import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { 
  Layers, 
  Users, 
  Info, 
  Compass, 
  Activity, 
  Sliders, 
  ChevronRight, 
  Sparkles, 
  Database 
} from 'lucide-react';
import { motion } from 'framer-motion';
import { getClusters, getClusterDetail } from '../api';
import ClusterBadge from '../components/ClusterBadge';
import LoadingState from '../components/LoadingState';
import ErrorState from '../components/ErrorState';
import ScientificDisclaimer from '../components/ScientificDisclaimer';

export default function Clusters() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [clustersData, setClustersData] = useState(null);
  const [selectedClusterId, setSelectedClusterId] = useState(id ? parseInt(id, 10) : 0);
  const [clusterDetail, setClusterDetail] = useState(null);
  const [loadingList, setLoadingList] = useState(true);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    setLoadingList(true);
    getClusters()
      .then((res) => {
        const data = res.data || res;
        setClustersData(data);
        setLoadingList(false);
      })
      .catch((err) => {
        console.error('Error fetching clusters:', err);
        setError(err.response?.data?.detail || err.message || 'Failed to load cluster profiles.');
        setLoadingList(false);
      });
  }, []);

  useEffect(() => {
    setLoadingDetail(true);
    getClusterDetail(selectedClusterId)
      .then((res) => {
        const data = res.data || res;
        setClusterDetail(data);
        setLoadingDetail(false);
      })
      .catch((err) => {
        console.error('Error fetching cluster detail:', err);
        setLoadingDetail(false);
      });
  }, [selectedClusterId]);

  const handleClusterSelect = (cId) => {
    setSelectedClusterId(cId);
    navigate(`/clusters/${cId}`, { replace: true });
  };

  if (loadingList) {
    return <LoadingState message="Loading K-Means Cluster Architecture (K = 4)..." />;
  }

  if (error || !clustersData) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16">
        <ErrorState message={error || 'Failed to retrieve cluster profiles.'} />
      </div>
    );
  }

  const { clusters = [], optimal_k = 4, silhouette_score } = clustersData;

  // Adapt clusterDetail properties
  const detailClusterInfo = clusterDetail?.cluster || clusterDetail;
  const detailSize = detailClusterInfo?.material_count ?? detailClusterInfo?.size ?? 0;
  const detailDesc = detailClusterInfo?.description || '';
  const detailMeans = detailClusterInfo?.feature_means ?? clusterDetail?.mean_raw_properties ?? {};
  const centroidStd = clusterDetail?.centroid_standardized || {};
  const repMaterials = clusterDetail?.representative_materials || [];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 text-xs font-mono text-accent-cyan uppercase tracking-wider">
            <Layers className="w-3.5 h-3.5" />
            <span>Unsupervised Machine Learning Partitioning</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-display font-bold text-white tracking-tight">
            K-Means Clusters (K = 4)
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-2xl">
            Descriptive groupings generated by K-Means clustering across the 6 standardized features. These represent statistical data clusters rather than experimentally validated material classes.
          </p>
        </div>

        <div className="bg-space-card/80 p-3 rounded-xl border border-white/10 text-xs font-mono text-right">
          <span className="text-slate-400 block text-[10px] uppercase">Silhouette Score</span>
          <span className="text-accent-cyan font-bold text-lg">
            {silhouette_score !== undefined && silhouette_score !== null
              ? Number(silhouette_score).toFixed(4)
              : '0.2351'}
          </span>
          <span className="text-slate-500 text-[10px] block">Global Cluster Separation</span>
        </div>
      </div>

      {/* 4 Cluster Overview Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        {clusters.map((c, idx) => {
          const isSelected = c.cluster_id === selectedClusterId;
          const isCluster3 = c.cluster_id === 3;
          const cSize = c.material_count ?? c.size ?? 0;
          const cLabel = c.label ?? c.profile_label ?? `Cluster ${c.cluster_id}`;
          const cMeans = c.feature_means ?? c.mean_properties ?? {};

          return (
            <motion.div
              key={c.cluster_id}
              onClick={() => handleClusterSelect(c.cluster_id)}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: idx * 0.08, ease: [0.22, 1, 0.36, 1] }}
              whileHover={{ y: -3, scale: 1.015 }}
              className={`cursor-pointer rounded-2xl p-5 border transition-all duration-300 space-y-4 ${
                isSelected
                  ? 'bg-space-card/95 border-accent-cyan shadow-xl shadow-accent-cyan/15 ring-1 ring-accent-cyan/50 scale-[1.01]'
                  : 'bg-space-card/60 hover:bg-space-card/80 border-white/10 hover:border-white/20'
              }`}
            >
              <div className="flex items-center justify-between">
                <ClusterBadge clusterId={c.cluster_id} />
                <span className="text-xs font-mono text-slate-400">
                  {cSize} materials ({c.percentage ? Number(c.percentage).toFixed(1) : ((cSize / 1056) * 100).toFixed(1)}%)
                </span>
              </div>

              <div>
                <h3 className="font-display font-bold text-base text-white">
                  {cLabel}
                </h3>
                <p className="text-xs text-slate-400 mt-1 line-clamp-2">
                  {isCluster3
                    ? 'Small cluster exhibiting distinctive/extreme descriptor characteristics.'
                    : c.description}
                </p>
              </div>

              {/* Mean properties preview */}
              <div className="pt-3 border-t border-white/5 grid grid-cols-2 gap-2 text-[11px] font-mono">
                <div className="bg-space-surface/80 p-2 rounded-lg">
                  <span className="text-slate-400 text-[9px] block">MEAN BAND GAP</span>
                  <span className="text-white font-semibold">
                    {cMeans.band_gap !== undefined
                      ? `${Number(cMeans.band_gap).toFixed(2)} eV`
                      : '—'}
                  </span>
                </div>
                <div className="bg-space-surface/80 p-2 rounded-lg">
                  <span className="text-slate-400 text-[9px] block">MEAN PERMITTIVITY</span>
                  <span className="text-white font-semibold">
                    {cMeans.poly_total !== undefined
                      ? Number(cMeans.poly_total).toFixed(2)
                      : '—'}
                  </span>
                </div>
              </div>

              <div className="text-[11px] font-mono text-accent-cyan flex items-center justify-between">
                <span>{isSelected ? 'Currently Inspecting' : 'Click to Inspect'}</span>
                <ChevronRight className={`w-3.5 h-3.5 transition-transform ${isSelected ? 'translate-x-1' : ''}`} />
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Selected Cluster Deep Inspection Panel */}
      {loadingDetail ? (
        <LoadingState message={`Loading details for Cluster ${selectedClusterId}...`} />
      ) : clusterDetail ? (
        <div className="bg-space-card/80 backdrop-blur-xl rounded-2xl p-6 sm:p-8 border border-white/10 space-y-8">
          
          {/* Header of Detail */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/10 pb-6">
            <div>
              <div className="flex items-center gap-3">
                <ClusterBadge clusterId={selectedClusterId} />
                <span className="text-xs font-mono text-slate-400">
                  {detailSize} Materials Total
                </span>
              </div>
              <h2 className="text-2xl sm:text-3xl font-display font-bold text-white mt-2">
                Cluster {selectedClusterId} Profile & Centroid
              </h2>
              <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-3xl">
                {selectedClusterId === 3
                  ? 'Small cluster exhibiting distinctive/extreme descriptor characteristics.'
                  : detailDesc}
              </p>
            </div>

            <Link
              to={`/explorer?cluster=${selectedClusterId}`}
              className="px-4 py-2 rounded-xl bg-space-surface hover:bg-white/10 border border-white/10 text-xs font-mono text-accent-cyan hover:text-white transition-all self-start flex items-center gap-2"
            >
              <Compass className="w-3.5 h-3.5" />
              <span>Explore All {detailSize} Materials</span>
            </Link>
          </div>

          {/* Centroid Coordinates & Mean Raw Properties */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            
            {/* Standardized Centroid */}
            <div className="bg-space-surface/70 rounded-xl p-5 border border-white/5 space-y-4">
              <div className="flex items-center gap-2">
                <Sliders className="w-4 h-4 text-accent-cyan" />
                <h3 className="font-display font-bold text-sm text-white uppercase tracking-wider">
                  Cluster Centroid (Standardized 6D Space)
                </h3>
              </div>
              <p className="text-xs text-slate-400">
                Center of mass in standardized feature space (Z-scores) defining this cluster.
              </p>

              <div className="space-y-2 font-mono text-xs">
                {centroidStd &&
                  Object.entries(centroidStd).map(([feat, val]) => (
                    <div
                      key={feat}
                      className="flex items-center justify-between p-2.5 rounded-lg bg-space-dark/60 border border-white/5"
                    >
                      <span className="text-slate-300">{feat}</span>
                      <span
                        className={`font-bold ${
                          Number(val) >= 0 ? 'text-accent-cyan' : 'text-rose-400'
                        }`}
                      >
                        {Number(val) >= 0 ? `+${Number(val).toFixed(4)}` : Number(val).toFixed(4)} σ
                      </span>
                    </div>
                  ))}
              </div>
            </div>

            {/* Mean Raw Properties */}
            <div className="bg-space-surface/70 rounded-xl p-5 border border-white/5 space-y-4">
              <div className="flex items-center gap-2">
                <Database className="w-4 h-4 text-accent-violet" />
                <h3 className="font-display font-bold text-sm text-white uppercase tracking-wider">
                  Mean Raw DFT Properties
                </h3>
              </div>
              <p className="text-xs text-slate-400">
                Average physical values for materials assigned to this cluster.
              </p>

              <div className="grid grid-cols-2 gap-3 font-mono text-xs">
                <div className="p-3 rounded-lg bg-space-dark/60 border border-white/5 space-y-1">
                  <span className="text-[10px] text-slate-400 block">BAND GAP</span>
                  <span className="text-base font-bold text-white block">
                    {detailMeans.band_gap !== undefined
                      ? `${Number(detailMeans.band_gap).toFixed(2)} eV`
                      : '—'}
                  </span>
                </div>

                <div className="p-3 rounded-lg bg-space-dark/60 border border-white/5 space-y-1">
                  <span className="text-[10px] text-slate-400 block">TOTAL PERMITTIVITY</span>
                  <span className="text-base font-bold text-white block">
                    {detailMeans.poly_total !== undefined
                      ? Number(detailMeans.poly_total).toFixed(2)
                      : '—'}
                  </span>
                </div>

                <div className="p-3 rounded-lg bg-space-dark/60 border border-white/5 space-y-1">
                  <span className="text-[10px] text-slate-400 block">ELECTRONIC PERMITTIVITY</span>
                  <span className="text-base font-bold text-white block">
                    {detailMeans.poly_electronic !== undefined
                      ? Number(detailMeans.poly_electronic).toFixed(2)
                      : '—'}
                  </span>
                </div>

                <div className="p-3 rounded-lg bg-space-dark/60 border border-white/5 space-y-1">
                  <span className="text-[10px] text-slate-400 block">DENSITY</span>
                  <span className="text-base font-bold text-white block">
                    {detailMeans.density !== undefined
                      ? `${Number(detailMeans.density).toFixed(2)} g/cm³`
                      : '—'}
                  </span>
                </div>
              </div>
            </div>

          </div>

          {/* Representative Materials Table */}
          {repMaterials.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="font-display font-bold text-base text-white">
                  Representative Materials (Closest to Centroid)
                </h3>
                <span className="text-xs font-mono text-slate-400">
                  Ranked by geometric proximity to centroid
                </span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left font-mono text-xs">
                  <thead>
                    <tr className="border-b border-white/10 text-slate-400 uppercase text-[10px]">
                      <th className="py-2.5 px-3">Material ID</th>
                      <th className="py-2.5 px-3">Formula</th>
                      <th className="py-2.5 px-3">Band Gap (eV)</th>
                      <th className="py-2.5 px-3">Permittivity (ε)</th>
                      <th className="py-2.5 px-3">Density (g/cm³)</th>
                      <th className="py-2.5 px-3 text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5 text-slate-300">
                    {repMaterials.map((m) => (
                      <tr key={m.material_id} className="hover:bg-white/5 transition-colors">
                        <td className="py-2.5 px-3 text-accent-cyan font-bold">
                          {m.material_id}
                        </td>
                        <td className="py-2.5 px-3 font-semibold text-white">
                          {m.formula}
                        </td>
                        <td className="py-2.5 px-3 text-slate-300">
                          {m.band_gap !== undefined ? `${Number(m.band_gap).toFixed(2)} eV` : '—'}
                        </td>
                        <td className="py-2.5 px-3 text-slate-300">
                          {m.poly_total !== undefined ? Number(m.poly_total).toFixed(2) : '—'}
                        </td>
                        <td className="py-2.5 px-3 text-slate-300">
                          {m.density !== undefined ? `${Number(m.density).toFixed(2)}` : '—'}
                        </td>
                        <td className="py-2.5 px-3 text-right">
                          <Link
                            to={`/material/${m.material_id}`}
                            className="text-xs text-accent-cyan hover:underline font-medium"
                          >
                            View Details →
                          </Link>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

        </div>
      ) : null}

      {/* Mandatory Scientific Disclaimer */}
      <ScientificDisclaimer />

    </div>
  );
}
